#include "DataFormats/ParticleFlowReco_Alpaka/interface/PFRecHitSoA.h"
#include "DataFormats/ParticleFlowReco_Alpaka/interface/CaloRecHitSoA.h"
#include "DataFormats/ParticleFlowReco_Alpaka/interface/PFClusterHostCollection.h"
#include "DataFormats/ParticleFlowReco_Alpaka/interface/PFClusterSoA.h"
#include "DataFormats/Common/interface/Wrapper.h"
