#include "HeterogeneousCore/AlpakaCore/interface/alpaka/typelookup.h"
#include "RecoParticleFlow/PFRecHitProducer/interface/alpaka/PFRecHitTopologyDeviceCollection.h"

TYPELOOKUP_ALPAKA_DATA_REG(PFRecHitHCALTopologyDeviceCollection);
TYPELOOKUP_ALPAKA_DATA_REG(PFRecHitECALTopologyDeviceCollection);
