#ifndef RecoParticleFlow_PFClusterProducerAlpaka_interface_JobConfigurationAlpakaRecord2_h
#define RecoParticleFlow_PFClusterProducerAlpaka_interface_JobConfigurationAlpakaRecord2_h

#include "FWCore/Framework/interface/EventSetupRecordImplementation.h"

class JobConfigurationAlpakaRecord2
    : public edm::eventsetup::EventSetupRecordImplementation<JobConfigurationAlpakaRecord2> {};

#endif  // RecoParticleFlow_PFRecHitProducer_interface_JobConfigurationAlpakaRecord_h
